Update PSG1208.yml

diff --git a/.github/workflows/PSG1208.yml b/.github/workflows/PSG1208.yml
--- a/.github/workflows/PSG1208.yml
+++ b/.github/workflows/PSG1208.yml
@@ -1,1 +1,66 @@
-PSG1208
+#修改TNAME: K2P 中的K2P为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
+name: PSG1208
+
+on: 
+  release:
+    types: [published]
+  push:
+    tags:
+    - 'v*'
+  #  branches: 
+  #    - master
+#  schedule:
+#    - cron: 0 8 * * 5
+#  workflow_dispatch:
+#  schedule:                                                    # 自动编译时间表
+#    - cron: 0 12 1 * *
+  watch:
+    types: [started]
+
+jobs:
+  build:
+    runs-on: ubuntu-20.04
+    if: github.event.repository.owner.id == github.event.sender.id
+
+    steps:
+    - name: Checkout
+      uses: actions/checkout@master
+    - name: Initialization environment
+      env:
+        DEBIAN_FRONTEND: noninteractive
+      run: |
+        sudo apt-get update
+        sudo apt-get install autoconf automake autopoint bison build-essential flex gawk gettext git gperf libtool pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev liblzma-dev texinfo python-docutils
+    - name: Clone source code
+      env:
+        KERNEL: 3.4
+      run: |
+        if [ $KERNEL = "4.4" ] ; then
+        git clone --depth=1 https://github.com/MeIsReallyBa/padavan-4.4.git /opt/rt-n56u
+        else
+        git clone --depth=1 https://github.com/sanjiaoban/rt-n56uandy.git /opt/rt-n56u
+        fi
+        cd /opt/rt-n56u/toolchain-mipsel
+        sudo ./clean_sources
+        sudo ./build_toolchain
+        mkdir -p /opt/images/
+    - name: Build Firmware
+      env:
+        TNAME: PSG1208
+      run: |
+        cd /opt/rt-n56u/trunk
+        if [ ! -f configs/templates/$TNAME.config ] ; then
+        echo "configs/templates/$TNAME.config not found "
+        exit 1
+        fi
+        cp -f configs/templates/$TNAME.config .config
+        sudo ./clear_tree
+        sudo ./build_firmware
+        sudo mv -f images/*.trx /opt/images/
+    - name : Upload packages
+      uses: actions/upload-artifact@master
+      if: always()
+      with:
+        name: Padavan-PSG1208
+        path: /opt/images
+
